version: '3.7'

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    ports:
      - '4002:4001'
    networks:
      - backend

  mongodb:
    image: mongo:4.2.1
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
