version: '3.7'

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - '4002:4001'
    networks:
      - backend

  mongodb:
    image: mongo:4.2.1
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
